//code generated by deepseek query
class Dice {
    /**
     * Rolls a single die.
     * @param {number} faces - Number of faces (e.g., 6 for a d6).
     * @returns {number} Random value between 1 and `faces`.
     */
    static roll(faces) {
        if (faces < 1) throw new Error("Dice must have at least 1 face.");
        return Math.floor(Math.random() * faces) + 1;
    }

    /**
     * Rolls multiple dice and sums the result.
     * @param {number} count - Number of dice to roll.
     * @param {number} faces - Faces per die.
     * @returns {number} Total result.
     */
    static rollMultiple(count, faces) {
        let total = 0;
        for (let i = 0; i < count; i++) {
            total += Dice.roll(faces);
        }
        return total;
    }
}